# https://kubernetes.io/docs/concepts/configuration/secret/
# all values in data should be base64 encoded
# we can encode them on Linux using 
# echo -n user | base64
# bW9uZ291c2Vy
# echo -n pass | base64
#bW9uZ29wYXNz
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # genric type to define secret data
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNz
