# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# we can have 2 different Files for deployment and service
# but as best practise we combine them
# https://hub.docker.com/_/mongo/tags?name=5.0
# we can label anything in K8


apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment #i dentifier for componenet
  labels: # Optional, deployement labels, additional identifier for component 
    app: webapp
spec:
  replicas: 2 # we will not scale, if we need to scale we use statefullset
  selector:
    matchLabels: 
      app: webapp # This part we are telling K8 that all pods matchs below label
      #Labels will be attached to this deplyement 
      # best practise to use app as key in K8 but key can be named anything
  template:
    metadata:
      labels: # Required, Pods label 
        app: webapp # Labels arenot unique ids as pod name , so in here we specified same lable for all replica pods
    spec:
      containers:
      - name: webapp # just name
        image: nanajanashia/k8s-demo-app:v1.0 # image:tag
        ports:
        - containerPort: 3000 #port
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user      
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password  
        - name: DB_URL
          valueFrom:  # name of component inside conf file 
            configMapKeyRef:
              name: mongo-config
              key: mongo-db-url  
# create seperate yaml syntax
# https://kubernetes.io/docs/concepts/services-networking/service/
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service # endpoint to access monogo defined on confmap
spec:
  type: NodePort
  selector:
    app: webapp # same as pod label
  ports:
    - protocol: TCP
      port: 3000 # access service common practise to be same as target "container port"
      targetPort: 3000 # same as container port
      nodePort: 31000 # from defined ports
